#include QMK_KEYBOARD_H

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_72us(
        KC_ESC,        KC_1,    KC_2,    KC_3,    KC_4,    KC_5,    KC_6,    QK_BOOT/*M1*/, XXXXXXX, XXXXXXX,  XXXXXXX, // C3
        KC_TAB,        KC_Q,    KC_W,    KC_E,    KC_R,    KC_T,    KC_T,    XXXXXXX/*M3*/, XXXXXXX, XXXXXXX,  KC_LWIN, // C5
        KC_CAPS_LOCK,  KC_A,    KC_S,    KC_D,    KC_F,    KC_G,    KC_G,    XXXXXXX/*M4*/, XXXXXXX, XXXXXXX,  XXXXXXX, // C7
        KC_LEFT_SHIFT, KC_Z,    KC_X,    KC_C,    KC_V,    KC_B,    KC_B,    XXXXXXX/*M5*/, XXXXXXX, XXXXXXX,  XXXXXXX, // C9
        XXXXXXX,       XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX/*M2*/, XXXXXXX, XXXXXXX,  XXXXXXX, // C4
        XXXXXXX,       XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX, XXXXXXX,  KC_LALT, // C6
        XXXXXXX,       XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       XXXXXXX, KC_SPACE, XXXXXXX, // C8
        XXXXXXX,       XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX, XXXXXXX,       KC_LCTL, XXXXXXX,  XXXXXXX  // C10
    )
};
